### ISSUE TITLE
What are minimum requirements to install SkyMake

### ISSUE THREAD

**Issue by GaneshKandu** [yigitkeremoktay/SkyMake#4]
Hi,

I am trying to install SkyMake but i am getting error.

What are minimum requirements to install SkyMake

I got error on mysql 5.5
```
CREATE TABLE `skymake_users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 

#1067 - Invalid default value for 'created_at'
```
on 5.6
```
ALTER TABLE 'skymake_examdata'
	ADD UNIQUE KEY 'examid' ('examid')

#1071 - Specified key was too long; max key length is 767 bytes
```
Its working on mysql 5.7

but I am getting a 404 error after successful installation on

Results > Courses Dashboard
Results > My Profile

I want installation steps with minimum PHP and MySQL requirement and file permissions to install SkyMake

**Comment by yigitkerem** [comment]
Hello!
Thanks for trying out. Can you supply your config files at "SkyMakeDatabaseConnector/SkyMakeDBconfig.php" and "SkyMakeConfiguration.php" as well as confirm the existence of .htaccess file?

Install instructions can be found here https://docs.theskyfallen.com/v/skymake (but they may be a bit outdated)
PHP 7.0 or newer is suggested. MYSQL 5.7 is correct and should be working.

**Comment by yigitkerem** [comment]
@GaneshKandu 
You can as well book a live support session at https://help.theskyfallen.com for further assistance.

**Comment by yigitkerem** [comment]
@GaneshKandu this issue will be closed because of inactivity within two business days.

**Comment by GaneshKandu** [comment]
> PHP 7.0 or newer is suggested. MYSQL 5.7 is correct and should be working.

Thanks! Working on PHP 7.0 and MYSQL 5.7.

> but I am getting a 404 error after successful installation on
> Results > Courses Dashboard
> Results > My Profile

this issue is still there.

> Question

is It run on apache and apache 2 also ? [https://github.com/yigitkeremoktay/SkyMake#prequisites](https://github.com/yigitkeremoktay/SkyMake#prequisites) i am using apache server

**Comment by yigitkerem** [comment]
> Hello!
> Thanks for trying out. Can you supply your config files at "SkyMakeDatabaseConnector/SkyMakeDBconfig.php" and "SkyMakeConfiguration.php" as well as confirm the existence of .htaccess file?
> 
> Install instructions can be found here https://docs.theskyfallen.com/v/skymake (but they may be a bit outdated)
> PHP 7.0 or newer is suggested. MYSQL 5.7 is correct and should be working.

@GaneshKandu please upload the debug files as suggested. Make sure you have updated SkyMake to the latest release by going to "Admin Interface -> About This Install -> Software Update". If you can't login as the admin make sure to import "install.sql" file into your database.

**Comment by GaneshKandu** [comment]
[SkyMakeDBconfig.php.txt](https://github.com/yigitkeremoktay/SkyMake/files/5481590/SkyMakeDBconfig.php.txt)
[SkyMakeConfiguration.php.txt](https://github.com/yigitkeremoktay/SkyMake/files/5481591/SkyMakeConfiguration.php.txt)

I downloaded ``SFR-204491`` version

> "Admin Interface -> About This Install -> Software Update"

No ``Software Update`` option 

![image](https://user-images.githubusercontent.com/12833130/97995187-34404480-1e0c-11eb-9867-1ceeaebe558d.png)

**Comment by yigitkerem** [comment]
> [SkyMakeDBconfig.php.txt](https://github.com/yigitkeremoktay/SkyMake/files/5481590/SkyMakeDBconfig.php.txt)
> [SkyMakeConfiguration.php.txt](https://github.com/yigitkeremoktay/SkyMake/files/5481591/SkyMakeConfiguration.php.txt)
> 
> I downloaded `SFR-204491` version
> 
> > "Admin Interface -> About This Install -> Software Update"
> 
> No `Software Update` option
> 
> ![image](https://user-images.githubusercontent.com/12833130/97995187-34404480-1e0c-11eb-9867-1ceeaebe558d.png)
@GaneshKandu 
This is SFR-204382 and not SFR-204491. Please update to the latest version by downloading it [FROM HERE](https://swupdate.theskyfallen.com/updatecheck/?appid=541a2fb0429491f158f100ce7dcb0b86&seed=Stable).

**Comment by yigitkerem** [comment]
Is the issue fixed now @GaneshKandu?

**Comment by GaneshKandu** [comment]
> Is the issue fixed now

yes !

**Comment by yigitkerem** [comment]
OK. Closing.
